add_test( ShellTest.TestFork /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.TestFork]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.TestFork PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.TestForkInBackground /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.TestForkInBackground]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.TestForkInBackground PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.TestForkMixed /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.TestForkMixed]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.TestForkMixed PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.TestWait /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.TestWait]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.TestWait PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.InvalidExecCommand /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.InvalidExecCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.InvalidExecCommand PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.TestInvalidCommand /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.TestInvalidCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.TestInvalidCommand PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.Pwd /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.Pwd]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.Pwd PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.PwdWithArgument /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.PwdWithArgument]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.PwdWithArgument PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.PathPrompt /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.PathPrompt]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.PathPrompt PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.Exit /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.Exit]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.Exit PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.ExitWithArgument /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.ExitWithArgument]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.ExitWithArgument PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.CdForward /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.CdForward]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.CdForward PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.CdBackward /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.CdBackward]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.CdBackward PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.CDInvalidArgument /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.CDInvalidArgument]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.CDInvalidArgument PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.InternalHelpCommand /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.InternalHelpCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.InternalHelpCommand PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.ExternalHelpCommand /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.ExternalHelpCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.ExternalHelpCommand PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.HelpCommandNoArgument /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.HelpCommandNoArgument]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.HelpCommandNoArgument PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.DisplayLast10Commands /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.DisplayLast10Commands]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.DisplayLast10Commands PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.DisplayArguments /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.DisplayArguments]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.DisplayArguments PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.MinimumCommandNumber /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.MinimumCommandNumber]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.MinimumCommandNumber PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.CommandReverseOrder /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.CommandReverseOrder]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.CommandReverseOrder PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.CorrectCommandNumber /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.CorrectCommandNumber]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.CorrectCommandNumber PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.ReRunPreviousCommand /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.ReRunPreviousCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.ReRunPreviousCommand PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.ReRunNthCommand /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.ReRunNthCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.ReRunNthCommand PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.ReRunCommandInHistory /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.ReRunCommandInHistory]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.ReRunCommandInHistory PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.IllegalHistoryCommand /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.IllegalHistoryCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.IllegalHistoryCommand PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.IllegalNthCommand /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.IllegalNthCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.IllegalNthCommand PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.CtrlCInformation /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.CtrlCInformation]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.CtrlCInformation PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.CtrlCNoCrash /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.CtrlCNoCrash]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.CtrlCNoCrash PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.CDWithoutArgument /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.CDWithoutArgument]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.CDWithoutArgument PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.CDHome /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.CDHome]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.CDHome PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.ChangeToHomeDirectory /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.ChangeToHomeDirectory]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.ChangeToHomeDirectory PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ShellTest.cdBack /home/cmpt201/a8-yinkak/shell_test [==[--gtest_filter=ShellTest.cdBack]==] --gtest_also_run_disabled_tests)
set_tests_properties( ShellTest.cdBack PROPERTIES WORKING_DIRECTORY /home/cmpt201/a8-yinkak SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( shell_test_TESTS ShellTest.TestFork ShellTest.TestForkInBackground ShellTest.TestForkMixed ShellTest.TestWait ShellTest.InvalidExecCommand ShellTest.TestInvalidCommand ShellTest.Pwd ShellTest.PwdWithArgument ShellTest.PathPrompt ShellTest.Exit ShellTest.ExitWithArgument ShellTest.CdForward ShellTest.CdBackward ShellTest.CDInvalidArgument ShellTest.InternalHelpCommand ShellTest.ExternalHelpCommand ShellTest.HelpCommandNoArgument ShellTest.DisplayLast10Commands ShellTest.DisplayArguments ShellTest.MinimumCommandNumber ShellTest.CommandReverseOrder ShellTest.CorrectCommandNumber ShellTest.ReRunPreviousCommand ShellTest.ReRunNthCommand ShellTest.ReRunCommandInHistory ShellTest.IllegalHistoryCommand ShellTest.IllegalNthCommand ShellTest.CtrlCInformation ShellTest.CtrlCNoCrash ShellTest.CDWithoutArgument ShellTest.CDHome ShellTest.ChangeToHomeDirectory ShellTest.cdBack)
